<h2>Modelling: Future Price Direction 2

Creating **baseline** logistic regression (LR) models for price direction prediction using 1, 5, 7, 14 and 20 day in-the-future direction labels.

In [1]:
# Load pre split data:
from project_paths import PRE_SPLIT_DATA_LR_PATH
import pandas as pd
print(PRE_SPLIT_DATA_LR_PATH)

data = pd.read_pickle(PRE_SPLIT_DATA_LR_PATH) #Contains Direction_1
data.head()

/Users/cameroncochrane/Data Projects/vlXsnPPgKKnWqEJB/data/processed/direction/lr/ind_data.pkl

Price,Close,High,Low,Open,Volume,Direction_1,SMA_7,EMA_7,IDR,ATR_4,RSI_14,MACD,MACD_signal,MACD_hist
33,382.845001,390.084015,378.252014,389.230988,16419000,1,389.398568,385.053349,11.832001,11.397491,36.470417,-3.112802,-7.666231,4.553430
34,386.475006,392.645996,380.834015,382.420990,14188900,0,387.342141,385.408763,11.811981,11.828239,38.000530,-2.514616,-6.635908,4.121292
35,383.157990,388.575989,382.248993,386.118011,11641300,0,385.682853,384.846070,6.326996,9.363243,37.120720,-2.281901,-5.765107,3.483206
36,358.416992,385.048004,356.446991,382.962006,26456900,0,382.234423,378.238800,28.601013,14.642998,31.299762,-4.047210,-5.421527,1.374317
37,358.345001,364.345001,353.304993,358.591003,15585700,0,378.603995,373.265351,11.040009,14.445000,31.284389,-5.389908,-5.415203,0.025295

In [2]:
X_1 = data.drop(columns=['Direction_1'])
y_1 = data['Direction_1']

In [3]:
print(X_1.shape)
X_1.head()

(4366, 13)

Price,Close,High,Low,Open,Volume,SMA_7,EMA_7,IDR,ATR_4,RSI_14,MACD,MACD_signal,MACD_hist
33,382.845001,390.084015,378.252014,389.230988,16419000,389.398568,385.053349,11.832001,11.397491,36.470417,-3.112802,-7.666231,4.553430
34,386.475006,392.645996,380.834015,382.420990,14188900,387.342141,385.408763,11.811981,11.828239,38.000530,-2.514616,-6.635908,4.121292
35,383.157990,388.575989,382.248993,386.118011,11641300,385.682853,384.846070,6.326996,9.363243,37.120720,-2.281901,-5.765107,3.483206
36,358.416992,385.048004,356.446991,382.962006,26456900,382.234423,378.238800,28.601013,14.642998,31.299762,-4.047210,-5.421527,1.374317
37,358.345001,364.345001,353.304993,358.591003,15585700,378.603995,373.265351,11.040009,14.445000,31.284389,-5.389908,-5.415203,0.025295

In [4]:
print(y_1.shape)
y_1.head()

(4366,)

33    1
34    0
35    0
36    0
37    0
Name: Direction_1, dtype: int64

In [5]:
# Data containing no-direction column (to systematically generate Direction_5, _7, etc, datasets)
nd_data = data.copy()
nd_data = nd_data.drop(columns=['Direction_1'])
nd_data.head()

Price,Close,High,Low,Open,Volume,SMA_7,EMA_7,IDR,ATR_4,RSI_14,MACD,MACD_signal,MACD_hist
33,382.845001,390.084015,378.252014,389.230988,16419000,389.398568,385.053349,11.832001,11.397491,36.470417,-3.112802,-7.666231,4.553430
34,386.475006,392.645996,380.834015,382.420990,14188900,387.342141,385.408763,11.811981,11.828239,38.000530,-2.514616,-6.635908,4.121292
35,383.157990,388.575989,382.248993,386.118011,11641300,385.682853,384.846070,6.326996,9.363243,37.120720,-2.281901,-5.765107,3.483206
36,358.416992,385.048004,356.446991,382.962006,26456900,382.234423,378.238800,28.601013,14.642998,31.299762,-4.047210,-5.421527,1.374317
37,358.345001,364.345001,353.304993,358.591003,15585700,378.603995,373.265351,11.040009,14.445000,31.284389,-5.389908,-5.415203,0.025295

In [8]:
from bta_direction_functions import add_direction

In [21]:
# Direction_5 (1 week)
data_5 = nd_data.copy()
data_5 = add_direction(data=data_5,shift=5)
data_5 = data_5.dropna().copy()
X_5 = data_5.drop(columns=['Direction_5'])
y_5 = data_5['Direction_5']
y_5.tail() # NaN values appear at the tail usually. Check for them
print(X_5.shape, y_5.shape)

(4361, 13) (4361,)

In [19]:
# Direction_10 (2 week)
data_10 = nd_data.copy()
data_10 = add_direction(data=data_10,shift=10)
data_10 = data_10.dropna().copy()
X_10 = data_10.drop(columns=['Direction_10'])
y_10 = data_10['Direction_10']
y_10.tail() # NaN values appear at the tail usually. Check for them
print(X_10.shape, y_10.shape)

(4356, 13) (4356,)

In [20]:
# Direction_20 (1 month)
data_20 = nd_data.copy()
data_20 = add_direction(data=data_20,shift=20)
data_20 = data_20.dropna().copy()
X_20 = data_20.drop(columns=['Direction_20'])
y_20 = data_20['Direction_20']
y_20.tail() # NaN values appear at the tail usually. Check for them
print(X_20.shape, y_20.shape)

(4346, 13) (4346,)

<h4>Train-Test Split:</h4>

In [22]:
from sklearn.model_selection import train_test_split

# Make sure to pass 'shuffle = False' to the function as we are dealing with temporal data:
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X_1, y_1, test_size=0.15, shuffle=False)
X_train_5, X_test_5, y_train_5, y_test_5 = train_test_split(X_5, y_5, test_size=0.15, shuffle=False)
X_train_10, X_test_10, y_train_10, y_test_10 = train_test_split(X_10, y_10, test_size=0.15, shuffle=False)
X_train_20, X_test_20, y_train_20, y_test_20 = train_test_split(X_20, y_20, test_size=0.15, shuffle=False)

In [7]:
print(f"X_train shape:{X_train_1.shape}")
print(f"X_test shape:{X_test_1.shape}")
print(f"y_train shape:{y_train_1.shape}")
print(f"y_test shape:{y_test_1.shape}")

X_train shape:(3711, 13)
X_test shape:(655, 13)
y_train shape:(3711,)
y_test shape:(655,)

<h4>LR Modelling:</h4>

Data processing required on the data post split:
- Scale the numerical data
- Convert to Series/Arrays. This is done by the scalers

Modelling:
- Base model
- Hypertuning

Should be a farily simple pipeline

For now the baseline model will contain all of the features (but with L1 regression). We will remove features according to the previous feature selection during the tuning process and when moving onto XGBoost.

Remember to use a different pipeline for each of the different timeframes.

In [26]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import RobustScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

*Direction_1*

In [31]:
numeric_features = X_1.columns # All of the features are numeric but we will make the distinction for transparency

numeric_pipeline_1 = Pipeline([
    ("scaler", RobustScaler()) # There were outliers in violin/box plots from last NB
])

preprocessor_1 = ColumnTransformer([
    ("numeric", numeric_pipeline_1, numeric_features)
])

lr_1 = LogisticRegression(
    penalty='l1',
    C = 1.0,
    random_state=13,
    solver='liblinear', #default 'lbfgs' not L1-compatiable
    max_iter=1000,
    l1_ratio=1.0
)

pipeline_1 = Pipeline([
    ("preprocessor", preprocessor_1),
    ("classifier", lr_1)
])

print(pipeline_1.named_steps)

pipeline_1.fit(X_train_1, y_train_1)

y_pred_1 = pipeline_1.predict(X_test_1)
p_up_1 = pipeline_1.predict_proba(X_test_1)[:,1] #Probabilities

print(classification_report(y_test_1, y_pred_1))

{'preprocessor': ColumnTransformer(transformers=[('numeric',
                                 Pipeline(steps=[('scaler', RobustScaler())]),
                                 Index(['Close', 'High', 'Low', 'Open', 'Volume', 'SMA_7', 'EMA_7', 'IDR',
       'ATR_4', 'RSI_14', 'MACD', 'MACD_signal', 'MACD_hist'],
      dtype='str', name='Price'))]), 'classifier': LogisticRegression(l1_ratio=1.0, max_iter=1000, penalty='l1', random_state=13,
                   solver='liblinear')}

/Users/cameroncochrane/Data Projects/vlXsnPPgKKnWqEJB/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1381: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

              precision    recall  f1-score   support

           0       0.51      0.87      0.64       334
           1       0.46      0.12      0.18       321

    accuracy                           0.50       655
   macro avg       0.48      0.49      0.41       655
weighted avg       0.48      0.50      0.42       655

*Direction_5*

In [32]:
numeric_features = X_5.columns # All of the features are numeric but we will make the distinction for transparency

numeric_pipeline_5 = Pipeline([
    ("scaler", RobustScaler()) # There were outliers in violin/box plots from last NB
])

preprocessor_5 = ColumnTransformer([
    ("numeric", numeric_pipeline_5, numeric_features)
])

lr_5 = LogisticRegression(
    penalty='l1',
    C = 1.0,
    random_state=13,
    solver='liblinear', #default 'lbfgs' not L1-compatiable
    max_iter=1000,
    l1_ratio=1.0
)

pipeline_5 = Pipeline([
    ("preprocessor", preprocessor_5),
    ("classifier", lr_5)
])

print(pipeline_5.named_steps)

pipeline_5.fit(X_train_5, y_train_5)

y_pred_5 = pipeline_5.predict(X_test_5)
p_up_5 = pipeline_5.predict_proba(X_test_5)[:,1] #Probabilities

print(classification_report(y_test_5, y_pred_5))

{'preprocessor': ColumnTransformer(transformers=[('numeric',
                                 Pipeline(steps=[('scaler', RobustScaler())]),
                                 Index(['Close', 'High', 'Low', 'Open', 'Volume', 'SMA_7', 'EMA_7', 'IDR',
       'ATR_4', 'RSI_14', 'MACD', 'MACD_signal', 'MACD_hist'],
      dtype='str', name='Price'))]), 'classifier': LogisticRegression(l1_ratio=1.0, max_iter=1000, penalty='l1', random_state=13,
                   solver='liblinear')}
              precision    recall  f1-score   support

         0.0       0.50      0.88      0.64       330
         1.0       0.46      0.10      0.16       325

    accuracy                           0.49       655
   macro avg       0.48      0.49      0.40       655
weighted avg       0.48      0.49      0.40       655

/Users/cameroncochrane/Data Projects/vlXsnPPgKKnWqEJB/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1381: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(