<h2>Modelling: Future Price Direction 2

In [5]:
# Load pre split data:
from project_paths import PRE_SPLIT_DATA_LR_PATH
import pandas as pd
print(PRE_SPLIT_DATA_LR_PATH)

data = pd.read_pickle(PRE_SPLIT_DATA_LR_PATH) #Contains Direction_1
data.head()

C:\Users\cochr\Data Science Projects\vlXsnPPgKKnWqEJB\data\processed\direction\lr\ind_data.pkl

Price,Close,High,Low,Open,Volume,Direction_1,SMA_7,EMA_7,IDR,ATR_4,RSI_14,MACD,MACD_signal,MACD_hist
33,382.845001,390.084015,378.252014,389.230988,16419000,1,389.398568,385.053349,11.832001,11.397491,36.470417,-3.112802,-7.666231,4.553430
34,386.475006,392.645996,380.834015,382.420990,14188900,0,387.342141,385.408763,11.811981,11.828239,38.000530,-2.514616,-6.635908,4.121292
35,383.157990,388.575989,382.248993,386.118011,11641300,0,385.682853,384.846070,6.326996,9.363243,37.120720,-2.281901,-5.765107,3.483206
36,358.416992,385.048004,356.446991,382.962006,26456900,0,382.234423,378.238800,28.601013,14.642998,31.299762,-4.047210,-5.421527,1.374317
37,358.345001,364.345001,353.304993,358.591003,15585700,0,378.603995,373.265351,11.040009,14.445000,31.284389,-5.389908,-5.415203,0.025295

In [7]:
X_1 = data.drop(columns=['Direction_1'])
y_1 = data['Direction_1']

In [13]:
print(X_1.shape)
X_1.head()

(4365, 13)

Price,Close,High,Low,Open,Volume,SMA_7,EMA_7,IDR,ATR_4,RSI_14,MACD,MACD_signal,MACD_hist
33,382.845001,390.084015,378.252014,389.230988,16419000,389.398568,385.053349,11.832001,11.397491,36.470417,-3.112802,-7.666231,4.553430
34,386.475006,392.645996,380.834015,382.420990,14188900,387.342141,385.408763,11.811981,11.828239,38.000530,-2.514616,-6.635908,4.121292
35,383.157990,388.575989,382.248993,386.118011,11641300,385.682853,384.846070,6.326996,9.363243,37.120720,-2.281901,-5.765107,3.483206
36,358.416992,385.048004,356.446991,382.962006,26456900,382.234423,378.238800,28.601013,14.642998,31.299762,-4.047210,-5.421527,1.374317
37,358.345001,364.345001,353.304993,358.591003,15585700,378.603995,373.265351,11.040009,14.445000,31.284389,-5.389908,-5.415203,0.025295

In [12]:
print(y_1.shape)
y_1.head()

(4365,)

33    1
34    0
35    0
36    0
37    0
Name: Direction_1, dtype: int64

In [19]:
# Data containing no-direction column (to systematically generate Direction_5, _7, etc, datasets)
nd_data = data.copy()
nd_data = nd_data.drop(columns=['Direction_1'])
nd_data.head()

Price,Close,High,Low,Open,Volume,SMA_7,EMA_7,IDR,ATR_4,RSI_14,MACD,MACD_signal,MACD_hist
33,382.845001,390.084015,378.252014,389.230988,16419000,389.398568,385.053349,11.832001,11.397491,36.470417,-3.112802,-7.666231,4.553430
34,386.475006,392.645996,380.834015,382.420990,14188900,387.342141,385.408763,11.811981,11.828239,38.000530,-2.514616,-6.635908,4.121292
35,383.157990,388.575989,382.248993,386.118011,11641300,385.682853,384.846070,6.326996,9.363243,37.120720,-2.281901,-5.765107,3.483206
36,358.416992,385.048004,356.446991,382.962006,26456900,382.234423,378.238800,28.601013,14.642998,31.299762,-4.047210,-5.421527,1.374317
37,358.345001,364.345001,353.304993,358.591003,15585700,378.603995,373.265351,11.040009,14.445000,31.284389,-5.389908,-5.415203,0.025295

<h4>Train-Test Split:</h4>

In [16]:
from sklearn.model_selection import train_test_split

# Make sure to pass 'shuffle = False' to the function as we are dealing with temporal data:
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X_1, y_1, test_size=0.15, shuffle=False)

In [17]:
print(f"X_train shape:{X_train_1.shape}")
print(f"X_test shape:{X_test_1.shape}")
print(f"y_train shape:{y_train_1.shape}")
print(f"y_test shape:{y_test_1.shape}")

X_train shape:(3710, 13)
X_test shape:(655, 13)
y_train shape:(3710,)
y_test shape:(655,)

<h4>Modelling:</h4>

Data processing required:
- Remove an NaN values
- Scale the numerical data
- Convert to Series/Arrays

Modelling:
- Base model
- Hypertuning

For now the baseline model will contain all of the features (but with L1 regression). We will remove features according to the previous feature selection during the tuning process.