<h2>Modelling: Future Price Direction 4 (LSTM)

<h3>Data Preparation

In [2]:
# Load pre split data:
from project_paths import RAW_DATA_PATH
import pandas as pd

from bta_direction_functions import add_direction
print(RAW_DATA_PATH)

raw_data = pd.read_pickle(RAW_DATA_PATH)
nd_data = raw_data.copy()
nd_data.head()

C:\Users\cochr\Data Science Projects\vlXsnPPgKKnWqEJB\data\raw\btcusd_data.pkl

Price       Date       Close        High         Low        Open    Volume
0     2014-09-17  457.334015  468.174011  452.421997  465.864014  21056800
1     2014-09-18  424.440002  456.859985  413.104004  456.859985  34483200
2     2014-09-19  394.795990  427.834991  384.532013  424.102997  37919700
3     2014-09-20  408.903992  423.295990  389.882996  394.673004  36863600
4     2014-09-21  398.821014  412.425995  393.181000  408.084991  26580100

In [4]:
data_20 = add_direction(data=nd_data, shift=20, price="Close")
data_20 = data_20.drop(columns=["Date"])
data_20.head()

Price       Close        High         Low        Open    Volume  Direction_20
0      457.334015  468.174011  452.421997  465.864014  21056800             0
1      424.440002  456.859985  413.104004  456.859985  34483200             0
2      394.795990  427.834991  384.532013  424.102997  37919700             0
3      408.903992  423.295990  389.882996  394.673004  36863600             0
4      398.821014  412.425995  393.181000  408.084991  26580100             0

In [6]:
from bta_direction_functions import add_EMA, add_SMA

Let's add _5 (1 week), _10 (2 week_), _20 (1 month) SMAs and EMAs. Leave out MACD, RSI and ATR.

In [7]:
data_20 = add_SMA(data=data_20,n=5,price="Close")
data_20 = add_SMA(data=data_20,n=10,price="Close")
data_20 = add_SMA(data=data_20,n=20,price="Close")

data_20 = add_EMA(data=data_20,n=5,price="Close")
data_20 = add_EMA(data=data_20,n=10,price="Close")
data_20 = add_EMA(data=data_20,n=20,price="Close")

In [9]:
data_20 = data_20.dropna().copy() # Drop NA rows
data_20.head()

Price,Close,High,Low,Open,Volume,Direction_20,SMA_5,SMA_10,SMA_20,EMA_5,EMA_10,EMA_20
19,330.079010,345.134003,302.559998,320.389008,79011800,1,342.807800,363.676599,389.910399,341.195946,359.626329,383.883180
20,336.187012,339.247009,320.481995,330.584015,49199900,1,335.030804,357.343301,383.853049,339.526301,355.364635,379.340688
21,352.940002,354.364014,327.187988,336.115997,54736300,1,333.716406,354.919202,380.278049,343.997535,354.923793,376.826337
22,365.026001,382.726013,347.687012,352.747986,83641104,0,340.948407,353.875101,378.789549,351.007024,356.760558,375.702495
23,361.562012,375.066986,352.963013,364.687012,43665700,0,349.158807,351.336902,376.422450,354.525353,357.633549,374.355783

- Remove Volume, Open, SMA_5, and Low in the modelling pipeline based on the feature selection from the previous notebook.
- Temporal train-test split.
- Scale numerical features on training split
- Add overlap sequences
- Train an LSTM.

In [ ]:
X = data_20.copy().drop['Direction_20']
y = data_20.copy()["Direction_20"]